AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Udemy Big Data Course Stack
Metadata:
  Authors:
    Description: Andrew Saushkin (asaushkin@gmail.com)
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - ShardCount
    ParameterLabels:
      - ShardCount:
          default: Number of Kinesis streams shards
Parameters:
  ShardCount:
    Default: 1
    Type: Number
Rules:
  RegionSupport:
    Assertions:
      - Assert:
          Fn::Contains:
            - - 'us-west-2'
            - !Ref 'AWS::Region'
        AssertDescription: This stack is only available in the US West (Oregon). Please launch the stack in one of these regions to continue.
Resources:

  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamodb.yaml

  Kinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: kinesis-s3.yaml
      Parameters:
        ShardCount: !Ref ShardCount
        S3BucketName: !Ref AWS::StackName

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        KinesisDataFirehose: !GetAtt Kinesis.Outputs.FirehosePurchaseLogs
        CadabraOrders: !GetAtt Kinesis.Outputs.CadabraOrders
        DynamoCadabraOrders: !GetAtt DynamoDB.Outputs.DynamoCadabraOrders
        KeyName: id_rsa
        InstanceType: t2.micro
        InstanceRole: EC2AdministratorRole

